[project]
name = "remail"
version = "0.1.0"
description = ""
license = "GPL-3.0-or-later"
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.12,<3.14"

dependencies = [
    "duckdb",
    "sqlmodel",
    "duckdb-engine",
    "exchangelib",
    "llama-index",
    "streamlit",
    "imapclient",
    "llama-cpp-python",
    "llama-index-vector-stores-chroma",
    "llama-index-embeddings-huggingface",
    "transformers",
    "sentence-transformers",
    "chromadb",
    "sqlalchemy",
    "llama-index-readers-database",
    "werkzeug",
    "keyring",
    "torchvision",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.8.4"
]

[project.scripts]
my-script = "remail.frontend:home"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["win-64"]

[tool.pixi.pypi-dependencies]
remail = { path = ".", editable = true }

[tool.pixi.tasks]
start = "streamlit run remail/frontend.py"
